### ISSUE TITLE
Extract description for events

### ISSUE THREAD

**Issue by georgf** [georgf/probe-scraper-dev#10]
The event parser doesn't extract descriptions yet. That should be fixed.

**Comment by Dexterp37** [comment]
Should we fix `parse_events.py` on mozilla-central?

**Comment by georgf** [comment]
We already made minor changes in the repo here.
I think we should finalize those parsers here, then merge the results into m-c?
I'll open an issue on that.

**Comment by georgf** [comment]
Moved to: https://github.com/mozilla/probe-scraper/issues/7
